### ISSUE TITLE
Some bad news i guess ?

### ISSUE THREAD

**Issue by Saltinbank-SyS** [indetectables-net/toolkit#15]
Hello my friend can you explain : i know the reason of WKE is flagged but the rest of it no clues ...
![image](https://github.com/indetectables-net/toolkit/assets/76784754/14874da9-78f7-441d-a33c-f99d4db38f52)

**Comment by xchwarze** [comment]
From readme:
Every tool has been downloaded from their original/official websites, but we still recommend you to use them with caution, specially those tools whose official pages are forum threads.
